### ISSUE TITLE
unable running through example_keras_qat.ipynb

### ISSUE THREAD

**Issue by liaorongfan** [sony/model_optimization#414]
### Issue Type

Bug

### Source

pip (model-compression-toolkit)

### MCT Version

1.4.0

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Python version

Python 3.7.15

### Describe the issue

```shell
AttributeError: module 'model_compression_toolkit' has no attribute 'keras_quantization_aware_training_init'
```

### Expected behaviour

```shell
runing through code cells in /tutorials/example_keras_qat.ipynb
```

### Code to reproduce the issue

```shell
file : /tutorials/example_keras_qat.ipynb

code cell:

def gen_representative_dataset():
    def _generator():
        for _img in x_train:
            yield [_img[np.newaxis, ...]]
    return _generator().__next__


qat_model, _, custom_objects = mct.keras_quantization_aware_training_init(model,
                                                                          gen_representative_dataset(),
                                                                          core_config=mct.CoreConfig(n_iter=10),
                                                                          target_platform_capabilities=get_tpc())

qat_model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
score = qat_model.evaluate(x_test, y_test, verbose=0)
print(f"PTQ model test accuracy: {score[1]:02.4f}")
```

### Log output

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-b30ae0c6896e> in <module>
      6 
      7 
----> 8 qat_model, _, custom_objects = mct.keras_quantization_aware_training_init(model,
      9                                                                           gen_representative_dataset(),
     10                                                                           core_config=mct.CoreConfig(n_iter=10),

AttributeError: module 'model_compression_toolkit' has no attribute 'keras_quantization_aware_training_init'
```

**Comment by elad-c** [comment]
Hi @liaorongfan ,

Quantization Aware Training (QAT) is a new feature that has been added to the latest release of MCT (version 1.6.0). From the issue we understand you are using MCT version 1.4.0 which doesn't include QAT. To use MCT QAT feature, please use our latest version.

**Comment by liaorongfan** [comment]
Hi @elad-c  Thank you, pip install mct default version is 1.4.0. and after installing from source (verison 1.6.0) it's ok now.

**Comment by elad-c** [comment]
Thanks for letting us know. We will look into that.

**Comment by elad-c** [comment]
Hi @liaorongfan ,
Indeed we found an issue in the MCT requirements, that combined with a python environment of python 3.7, caused the MCT version to fallback to 1.4.0. A fix was inserted and will be published in the next release.
As a temporary workaround, you can work with python 3.8 or above.
